window.LETOM_SEARCH_INDEX = [
  {
    type: "Blesková správa",
    title: "Druhý požiar na Zakynthose: z oblasti Elies už nariadili evakuáciu smerom na Volimes",
    description: "Po rannom ohnisku pri Marathiase vypukol krátko pred 13:00 ďalší požiar v oblasti Volimes na severe Zakynthosu.",
    url: "spravy/zakynthos-druhy-poziar-volimes-evakuacia-2026.html",
    keywords: "zakynthos zante druhy poziar volimes elies evakuacia 112 marathias keri grecko hasici emode",
  },
  {
    type: "Blesková správa",
    title: "Požiar na Zakynthose. Obyvateľom a turistom prišla výstraha 112",
    description: "Na gréckom ostrove Zakynthos vypukol dnes ráno lesný požiar v oblasti Marathias pri Keri na juhozápade ostrova.",
    url: "spravy/zakynthos-poziar-marathias-112-2026.html",
    keywords: "zakynthos zante poziar marathias keri grecko vystraha 112 evakuacia hasiči lietadla vrtulniky",
  },
  {
    type: "Blesková správa",
    title: "Etna komplikuje lety v Catanii. Požiare v Stredomorí: aktuálna situácia",
    description: "Sopečný popol z Etny narušil prevádzku letiska Catania. V Španielsku pokračuje rozsiahly požiar pri Niebla, grécke ostrovy zostávajú vo veľmi vysokom stupni požiarneho rizika a Francúzsko preventívne uzavrelo štyri lesné oblasti vo Var.",
    url: "spravy/etna-catania-poziare-aktualna-situacia-2026.html",
    keywords: "etna catania sicilia sopka popol lety letisko poziare niebla huelva tirig castellon grecko poziarne riziko var francuzsko gros bessillon",
  },
  {
    type: "Hra",
    title: "Cesta za miliónom zážitkov | Majster Stredomoria",
    description: "15 otázok, tri nápovedy a cesta až k miliónu stredomorských míľ.",
    url: "kvizy/majster-stredomoria.html",
    keywords: "majster stredomoria cesta za milionom zazitkov hra vedomostna sutaz kvíz kviz 15 otazok napovedy stredomorie",
  },
  {
    type: "Článok",
    title: "Talian pracuje na kávu 11 minút, Slovák 23. A Grék? Prekvapivé porovnanie Stredomoria",
    description: "Porovnanie cien cappuccina, piva a bežného obeda cez počet minút práce v krajinách Stredomoria a na Slovensku.",
    url: "blog/talian-pracuje-na-kavu-11-minut-slovak-23-a-grek.html",
    keywords: "káva kava cappuccino pivo obed ceny mzdy platy pracovný čas taliansko španielsko francúzsko slovinsko malta chorvátsko cyprus slovensko grécko numbeo eurostat",
  },
  {
    type: "Kvíz",
    title: "Čo si nalejete pri mori? Kvíz o tradičnom alkohole Stredomoria",
    description: "12 otázok, v ktorých podľa tradičných likérov, destilátov a vín hádate destináciu Stredomoria.",
    url: "kvizy/tradicny-alkohol-stredomoria.html",
    keywords: "kvíz kviz alkohol tradície tradicie nápoje napoje ouzo grécko grecko raki kréta kreta mastiha chios limoncello amalfi sorrento mirto sardínia sardinia rakija chorvátsko chorvatsko maraschino zadar bajtra malta zivania cyprus pastis provence marseille sangria španielsko spanielsko teran slovinský kras stredomorie",
  },
  {
    type: "Kvíz",
    title: "Kde v Stredomorí sa nakrúcal Bond, Krstný otec či Star Wars?",
    description: "12 otázok o konkrétnych filmových lokáciách Stredomoria, vždy s tromi postupne odhaľovanými indíciami.",
    url: "kvizy/filmove-lokacie-stredomoria.html",
    keywords: "kvíz kviz filmy seriály serialy nakrúcanie nakrucanie lokácie lokacie bond no time to die matera krstný otec krstny otec savoca delá z navarone dela z navarone rodos mamma mia vis hra o trony split talented mr ripley ischia bourne mykonos biely lotos taormina indiana jones popeye malta il postino salina the tourist benatky stredomorie",
  },
  {
    type: "Článok",
    title: "Leto, ktoré sa nechce skončiť: čo objaviť medzi Larnakou a Paralimni",
    description: "Objavujeme Stredomorie · 1. časť: pláže, Cape Greco, Varoša aj praktické tipy z cesty po východnom Cypre.",
    url: "blog/cyprus-larnaka-paralimni-objavujeme-stredomorie-1.html",
    keywords: "cyprus larnaka paralimni ayia napa nissi beach cape greco protaras varoša varosha famagusta korytnačky musan pláže doprava autobus objavujeme stredomorie",
  },
  {
    type: "Článok",
    title: "Sardínia sa bála mora, Neapol chráni vajce: 8 neuveriteľných príbehov Stredomoria",
    description: "Bezcenné pobrežie, magické vajce, karanténa aj najstarší analógový počítač v ôsmich príbehoch Stredomoria.",
    url: "blog/8-neuveritelnych-pribehov-stredomoria.html",
    keywords: "sardínia costa smeralda malorka prak neapol vajce spinalonga dubrovník karanténa antikythéra pompeje colobraro história legendy stredomorie",
  },
  {
    type: "Článok",
    title: "Sardínia, ktorú treba zažiť autom: od Alghera cez La Maddalenu až po tyrkysové pláže San Teodora",
    description: "Osemdňový roadtrip priamym letom z Bratislavy, kompletný itinerár aj rozpočet pre štyroch dospelých.",
    url: "blog/sardinia-roadtrip-alghero-la-maddalena-san-teodoro.html",
    keywords: "sardínia sardinia alghero castelsardo palau la maddalena caprera san teodoro roadtrip auto bratislava ryanair taliansko pláže rozpočet",
  },
  {
    type: "Blesková správa",
    title: "Štrajk v Barcelone už ruší lety, lietadlá odleteli bez batožiny",
    description: "Najmenej 16 letov bolo do poludnia zrušených; ďalšie dve lietadlá odleteli bez podanej batožiny.",
    url: "spravy/barcelona-groundforce-rusenie-letov-2026.html",
    keywords: "Barcelona El Prat Groundforce štrajk zrušené lety batožina CGT meškanie",
  },
  {
    type: "Článok",
    title: "Požiare v Stredomorí 2026: obete, evakuovaní turisti a sezóna, ktorá sa ešte nekončí",
    description: "Kde zasiahli turistov, čo sa deje teraz a čo môže priniesť zvyšok sezóny.",
    url: "blog/poziare-v-stredomori-2026.html",
    keywords: "požiare 2026 stredomorie evakuácia turisti grécko taliansko španielsko francúzsko bezpečnosť",
  },
  {
    type: "Článok",
    title: "Má Stredomorie vlastnú vlajku? Takto by jeho symbol a vlajka vyzerali podľa AI",
    description: "Skúmali sme, či existuje spoločný symbol Stredomoria – a ako by jeho vlajka a znak mohli vyzerať podľa AI.",
    url: "blog/ma-stredomorie-vlastnu-vlajku.html",
    keywords: "stredomorie vlajka symbol znak únia pre stredomorie ufm stredomorské hry olivovník oliva more slnko ai umelá inteligencia",
  },
  {
    type: "Článok",
    title: "Francúzska riviéra bez milionárskeho rozpočtu: Nice, Cannes, Menton aj dedinky nad morom",
    description: "Ako sa tam dostať zo Slovenska, kde sa ubytovať a čo vidieť za 5 až 7 dní.",
    url: "blog/francuzska-riviera-bez-milionarskeho-rozpoctu.html",
    keywords: "francúzska riviéra francuzska riviera côte d’azur nice cannes menton antibes èze monako bratislava wizz air vlak francúzsko francuzsko",
  },
  {
    type: "Kvíz",
    title: "Kam k moru? Nájdite destináciu aj štýl dovolenky pre vás",
    description: "Osobnostný cestovateľský kvíz podľa pláží, jedla, prírody, miest, tempa a štýlu dovolenky od all inclusive po cestu na vlastnú päsť.",
    url: "kvizy/ktora-stredomorska-destinacia-je-pre-vas.html",
    keywords: "kvíz kviz osobnostný osobnostny destinácia destinacia dovolenka all inclusive na vlastnú päsť vlastnu pest more pláže plaze jedlo príroda priroda grécko grecko taliansko španielsko spanielsko chorvátsko chorvatsko malta cyprus"
  },
  {
    type: "Blesková správa",
    title: "Požiare už zasahujú aj východ Stredomoria",
    description: "Aktuálne informácie o požiaroch na Parose, Kréte, v Španielsku a Francúzsku aj praktické pokyny pre dovolenkárov.",
    url: "spravy/poziare-vychod-stredomoria-2026.html",
    keywords: "požiare Grécko Paros Kréta Rethymno Španielsko Francúzsko 112 evakuácia bezpečnosť"
  },
  {
    type: "Blesková správa",
    title: "Ryanair spustil 24-hodinový výpredaj: z Bratislavy k moru približne od 15 eur",
    description: "Krátky „pay day“ výpredaj leteniek do prímorských destinácií. Akcia sa podľa oznámenia končí 29. júla o 23:59.",
    url: "spravy/ryanair-24-hodinovy-vypredaj-2026.html",
    keywords: "Ryanair výpredaj letenky Bratislava Korfu Malta Zadar Košice batožina"
  },
  {
    type: "Článok",
    title: "Malorka na bicykli: kompletný sprievodca pre cykloturistov",
    description: "Kedy vyraziť, kde sa ubytovať, ktoré trasy zvládnu rekreační cyklisti a kedy sa oplatí vziať vlastný bicykel lietadlom?",
    url: "blog/malorka-na-bicykli.html",
    keywords: "malorka mallorca bicykel cyklistika cykloturistika španielsko spanielsko serra de tramuntana sa calobra cap de formentor port de pollença alcúdia požičovňa bicyklov ebike gravel ryanair austrian smartwings",
  },
  {
    type: "Článok",
    title: "Letenky zo Slovenska zlacneli o 45 %. Stredomorie je však ešte zaujímavejší príbeh",
    description: "Ceny leteckej dopravy na Slovensku v júni 2026 medziročne klesli o 45,1 %. Čo to znamená pre lety do Stredomoria?",
    url: "blog/letenky-slovensko-zlacneli-45-percent.html",
    keywords: "letenky slovensko slovaci letecká doprava letecka doprava eurostat ceny zlacnenie 45,1 percenta bratislava letisko konkurencia ryanair wizz air smartwings stredomorie taliansko španielsko spanielsko grécko grecko cyprus turecko sicília sicilia barcelona malaga alicante neapol palermo atény ateny larnaka antalya košice kosice",
  },
  {
    type: "Sekcia",
    title: "Hry pre deti",
    description: "Pokojné prázdninové hry s Čajkou Leto pre malých objaviteľov.",
    url: "deti/index.html",
    keywords: "deti hry čajka leto omaľovánka ukryte predmety",
  },
  {
    type: "Hra pre deti",
    title: "Vyfarbi Stredomorie",
    description: "Jednoduchá digitálna omaľovánka so šiestimi stredomorskými obrázkami.",
    url: "deti/vyfarbi-stredomorie.html",
    keywords: "deti omaľovánka vyfarbi stredomorie lietadlo delfín pláž loďka maják ostrov",
  },
  {
    type: "Hra pre deti",
    title: "Nájdi ukryté predmety",
    description: "Jemná prázdninová hra s Čajkou Leto pre malých objaviteľov.",
    url: "deti/ukryte-predmety.html",
    keywords: "deti hra ukryte predmety čajka leto pláž letisko prístav",
  },
  {
    type: "Mapa",
    title: "Mapa Stredomoria",
    description: "Interaktívna mapa krajín, ostrovov, miest, článkov, videí, podcastov, trás a aktuálnych upozornení.",
    url: "mapa.html",
    keywords: "mapa stredomorie krajiny ostrovy mestá clanky články videá videa podcasty itineráre itinerare lety upozornenia lefkada kos zakynthos",
  },
  {
    type: "Kvíz",
    title: "Kvízy o Stredomorí",
    description: "Prehľad interaktívnych kvízov o európskom Stredomorí: vedomostné otázky aj pátranie podľa indícií.",
    url: "kvizy/index.html",
    keywords: "kvízy kvizy stredomorie vedomostný kvíz kviz destinácie destinacie indície indicie otázky otazky",
  },
  {
    type: "Kvíz",
    title: "Veľký stredomorský kvíz",
    description: "15 otázok o krajinách, ostrovoch, mestách, jedle a prírode európskeho Stredomoria.",
    url: "kvizy/velky-stredomorsky-kviz.html",
    keywords: "kvíz kviz stredomorie otázky otazky grécko grecko taliansko španielsko spanielsko chorvátsko chorvatsko cyprus malta francúzsko francuzsko slovinsko ostrovy mestá mesta príroda priroda jedlo",
  },
  {
    type: "Kvíz",
    title: "Uhádnite stredomorskú destináciu podľa troch indícií",
    description: "Spoznajte 15 ostrovov, miest a pobreží Stredomoria podľa postupne odhaľovaných stôp.",
    url: "kvizy/uhadni-stredomorsku-destinaciu.html",
    keywords: "kvíz kviz destinácia destinacie indície indicie hádanie hadanie ostrovy mestá mesta pobrežie stredomorie",
  },
  {
    type: "Kvíz",
    title: "Uhádnete najnečakanejšie miesta Stredomoria?",
    description: "15 prekvapivých miest Stredomoria podľa troch indícií: púšť, sneh, ružové saliny, sopky aj jazykové ostrovy.",
    url: "kvizy/uhadnete-najnecakanejsie-miesta-stredomoria.html",
    keywords: "kvíz kviz najnečakanejšie miesta stredomorie indície indicie púšť tabernas troodos ružové saliny sopky elafonissi stromboli",
  },
  {
    type: "Kvíz",
    title: "NAJ kvíz o Stredomorí",
    description: "16 otázok o najväčších ostrovoch, najvyšších vrchoch a najstarších pamiatkach Stredomoria.",
    url: "kvizy/naj-stredomoria.html",
    keywords: "kvíz kviz naj stredomorie najväčší najvacsi najmenší najmensi najvyšší najvyssi najstarší najstarsi ostrovy vrchy pamiatky grécko grecko taliansko španielsko spanielsko chorvátsko chorvatsko malta cyprus francúzsko francuzsko slovinsko",
  },
  {
    type: "Kvíz",
    title: "Viete, čo si objednávate? Kvíz o chutiach Stredomoria",
    description: "16 otázok o jedlách, nápojoch, syroch, dezertoch a miestnych špecialitách Stredomoria.",
    url: "kvizy/chute-stredomoria.html",
    keywords: "kvíz kviz chute jedlo jedlá jedla nápoje napoje syry dezerty špeciality arancini focaccia paella souvlaki cannoli pašticada pasticada ensaimada bouillabaisse halloumi pastizzi stredomorie",
  },
  {
    type: "Kvíz",
    title: "Dohovorili by ste sa na dovolenke?",
    description: "16 otázok o pozdravoch, poďakovaní a praktických cestovateľských frázach v jazykoch Stredomoria.",
    url: "kvizy/dohovorili-by-ste-sa.html",
    keywords: "kvíz kviz jazyky frázy frazy dovolenka cestovanie taliančina taliancina gréčtina grectina španielčina spanielcina chorvátčina chorvatcina francúzština francuzstina maltčina maltcina slovinčina slovincina ciao grazie hola gracias hvala",
  },
  {
    type: "Článok",
    title: "Lefkada autom: 3 ubytovania v Agios Nikitas",
    description: "Porovnanie troch možností pre štyroch dospelých: cena, poloha pri plážach, stravovanie a praktické kompromisy.",
    url: "blog/lefkada-autom-3-ubytovania-agios-nikitas.html",
    keywords: "lefkada agios nikitas ubytovanie auto autom anthia melikiron milos paradise mylos kathisma pláže grécko grecko vila apartmán štúdio studio bazén cestovanie autom",
  },
  {
    type: "Článok",
    title: "5 zaujímavostí zo Stredomoria, o ktorých nie každý vie – 3. časť",
    description: "Tajomstvá Ríma, Barcelony, Palerma, Atén a Dubrovníka: pyramída, Eixample, qanat, Anafiotika a Lazareti.",
    url: "blog/5-zaujimavosti-stredomoria-3.html",
    keywords: "5 zaujímavostí stredomoria zaujimavosti seriál 3 časť rím rim cestiova pyramída cestiova pyramida barcelona eixample palermo qanat atény ateny anafiotika dubrovník dubrovnik lazareti taliansko španielsko spanielsko grécko grecko chorvátsko chorvatsko",
  },
  {
    type: "Flash správa",
    title: "Sedem gréckych ostrovov rieši vážny nedostatok vody",
    description: "Sedem gréckych ostrovov je v administratívnom núdzovom režime pre nedostatok vody. Praktické odporúčanie pre turistov pred cestou.",
    url: "spravy/grecke-ostrovy-nedostatok-vody-2026.html",
    keywords: "grécko grecko ostrovy voda nedostatok vody sucho astypalaia tinos alonnisos leros patmos symi karpathos hotel vodovod odsoľovanie obmedzenia dovolenka",
  },
  {
    type: "Flash správa",
    title: "Taliansko dnes zasiahne letecký štrajk, easyJet už ruší niektoré lety",
    description: "Letecký štrajk v Taliansku môže 21. júla ovplyvniť lety easyJetu aj ďalších dopravcov. Praktické odporúčanie pre cestujúcich.",
    url: "spravy/taliansko-letecky-strajk-easyjet-2026.html",
    keywords: "taliansko letecký štrajk letecky strajk easyjet 21 júl 2026 miláno malpensa linate rím fiumicino neapol salerno lamezia terme olbia alghero zrušené lety meskanie garantované lety enac",
  },
  {
    type: "Článok",
    title: "EÚ schválila nové práva cestujúcich",
    description: "Čo sa mení pri meškaní, kompenzácii, batožine, sedení detí a kedy nové pravidlá začnú platiť.",
    url: "blog/nove-prava-cestujucich-eu-2026.html",
    keywords: "eú eu práva cestujúcich prava cestujucich lietadlo letecká doprava letecka doprava meškanie meskanie kompenzácia kompenzacia batožina batozina príručná batožina prirucna batozina sedenie detí sedadlá refundácia voucher náhradná doprava palubný lístok eu261 nariadenie 261/2004",
  },
  {
    type: "Flash správa",
    title: "Ďalšia slovenská cestovka končí: Solvex vyhlásil platobnú neschopnosť",
    description: "Solvex po 26 rokoch oznámil platobnú neschopnosť. Praktický postup pre klientov v zahraničí aj pred odchodom.",
    url: "spravy/solvex-platobna-neschopnost-2026.html",
    keywords: "solvex cestovná kancelária cestovna kancelaria platobná neschopnosť platobna neschopnost colonnade poistenie proti úpadku poistenie proti upadku global assistance 421 911 803 500 8-893-015952 klienti zájazd reklamácia odškodnenie dovolenka",
  },
  {
    type: "Flash správa",
    title: "Avion a IKEA menia parkovanie: neobmedzené státie zadarmo končí",
    description: "Parkovanie pri Avione a IKEA už nebude bez časového obmedzenia zdarma. Prvé 3 hodiny cez pracovný týždeň a 5 hodín cez víkendy zostanú zdarma.",
    url: "spravy/avion-ikea-parkovanie-bratislava-2026.html",
    keywords: "avion ikea bratislava parkovanie letisko parkovisko zdarma tri 3 hodiny pat 5 vikend sviatok odlet auto cestovanie záchytné miesto regulácia rampe parkomat",
  },
  {
    type: "Článok",
    title: "Navagio chcú obnoviť do leta 2027. Otvorenie slávnej pláže však zatiaľ potvrdené nie je",
    description: "Plánované práce majú skončiť do leta 2027, o otvorení pláže však rozhodnú až bezpečnostné posudky.",
    url: "blog/navagio-obnova-leto-2027.html",
    keywords: "navagio zakynthos grécko grecko pláž plaz panagiotis vrak obnova leto 2027 otvorenie bezpečnosť bezpecnost útesy utesy zosuvy civilná ochrana civilna ochrana vyhliadka",
  },
  {
    type: "Flash správa",
    title: "Turistické pasce leta 2026: na týchto päť trikov si dajte pozor",
    description: "Pozor na taxíky bez taxametra, falošné petície, darčeky zadarmo, nejasné príplatky a podozrivo vysoké účty.",
    url: "spravy/turisticke-pasce-leto-2026.html",
    keywords: "turistické pasce turisticke pasce podvody dovolenka atény ateny taxík taxik taxameter pireus barcelona falošná petícia falosna peticia rím rim darček náramok naramok zmrzlina chorvátsko chorvatsko klub účet ucet 112 bezpečnosť cestovanie",
  },
  {
    type: "Článok",
    title: "Španielsko je vo finále MS: kde zažiť futbalovú noc",
    description: "Praktický sprievodca: veľké obrazovky, bary, doprava, horúčavy a krátky pobyt pri mori.",
    url: "blog/spanielsko-vo-finale-ms-2026.html",
    keywords: "španielsko spanielsko finále finale majstrovstvá sveta ms 2026 futbal madrid valencia alicante barcelona málaga malaga costa blanca costa del sol mallorca kanárske ostrovy kanarske ostrovy veľká obrazovka verejné premietanie verejne premietanie fanúšikovia fanusikovia dovolenka more krátky pobyt kratky pobyt lety zo slovenska",
  },
  {
    type: "Článok",
    title: "Dovolenka s cestovkou alebo bez nej? Veľké porovnanie ceny, pohodlia a slobody",
    description: "Porovnanie ceny, pohodlia a slobody pri dovolenke s cestovkou, bez cestovky, s all inclusive aj mimo hlavnej sezóny.",
    url: "blog/dovolenka-s-cestovkou-alebo-bez-nej.html",
    keywords: "dovolenka cestovka cestovná kancelária bez cestovky individuálna dovolenka all inclusive transfer delegát letenka ubytovanie prenájom auta grécko cyprus taliansko sardínia malta španielsko chorvátsko cena pohodlie sloboda",
  },
  {
    type: "Podcast",
    title: "Dovolenka s cestovkou alebo bez nej?",
    description: "Podcast k článku o tom, kedy dáva zmysel cestovka, kedy individuálna cesta a ako porovnať cenu, pohodlie a slobodu.",
    url: "audio.html",
    keywords: "podcast spotify dovolenka cestovka cestovná kancelária bez cestovky individuálna dovolenka all inclusive transfer delegát letenka ubytovanie prenájom auta grécko cyprus taliansko sardínia malta španielsko chorvátsko francúzsko slovinsko cena pohodlie sloboda",
  },
  {
    type: "Flash správa",
    title: "Cyprus a Grécko patria medzi európsku špičku v kvalite vody",
    description: "EEA: všetky sledované pobrežné vody na Cypre boli v roku 2025 výborné, v Grécku ich takto hodnotili 97,1 %.",
    url: "spravy/cyprus-grecko-kvalita-vody-2026.html",
    keywords: "cyprus grécko grecko kvalita vody more kúpanie kupanie EEA európska environmentálna agentúra pláže plaze e coli enterokoky teplota mora júl jul rodos kos kréta kreta zakynthos malta sicília sicilia chorvátsko chorvatsko mallorca costa del sol",
  },
  {
    type: "Článok",
    title: "5 zaujímavostí Stredomoria, o ktorých nie každý vie: 2. časť",
    description: "Zingaro na Sicílii, korytnačie pláže Zakynthosu, divoký Kos, sardínske dediny a Varosha na Cypre.",
    url: "blog/5-zaujimavosti-stredomoria-2.html",
    keywords: "stredomorie zaujímavosti zaujimavosti seriál serial druhá časť druha cast sicília sicilia zingaro san vito lo capo monte monaco zakynthos zakyntos korytnačky korytnacky laganas caretta caretta kos cavo paradiso therma springs nisyros sardínia sardinia castelsardo bosa tinnura flussio cyprus ayia napa protaras cape greco varosha famagusta",
  },
  {
    type: "Flash správa",
    title: "Wizz Air mení lety z Bratislavy: dve linky končia, ďalšie tri budú sezónne",
    description: "Dortmund a Plovdiv majú po lete skončiť; Nice, Ochrid a Lamezia Terme majú byť počas zimy mimo ponuky.",
    url: "spravy/wizz-air-bratislava-zmeny-zima-2026.html",
    keywords: "wizz air bratislava dortmund plovdiv nice ohrid lamezia terme zima 2026 2027 agadir hurgada hurghada baku letový poriadok linky",
  },
  {
    type: "Článok",
    title: "Čo si môžete priniesť z dovolenky v EÚ a mimo EÚ",
    description: "Praktický prehľad darčekov, colných limitov, potravín a suvenírov, ktoré môžu skončiť na colnici.",
    url: "blog/co-si-mozete-priniest-z-dovolenky-eu-mimo-eu.html",
    keywords: "suveníry suveniry darčeky darceky colnica clo limit EÚ EU mimo EÚ Turecko Egypt Tunisko Maroko alkohol tabak potraviny mäso maso syr rastliny mušle musle koraly CITES starožitnosti starozitnosti tekutiny príručná batožina batozina duty free dovolenka",
  },
  {
    type: "Článok",
    title: "Je plavba výletnou loďou po Stredomorí vhodná pre Slovákov?",
    description: "Kompletný sprievodca pre Slovákov: ceny, doprava do prístavu, kajuty, strava, výlety aj skryté poplatky.",
    url: "blog/plavba-vyletnou-lodou-stredomorie.html",
    keywords: "plavba výletná loď vyletna lod cruise stredomorie slovaci slovensko ceny doprava prístav pristav trieste benátky benatky ravenna civitavecchia barcelona piraeus kajuta kajuty balkón balkon strava výlety vylety poplatky servisné poplatky msc costa royal caribbean",
  },
  {
    type: "Článok",
    title: "Kos osobne: vietor, Poseidónov mobil a pláže",
    description: "Osobná skúsenosť z gréckeho Kosu z roku 2025: Caravia Beach, vietor, auto, Plaka Forest, Asklepion, Therma Springs, Zia, Kefalos a Cavo Paradiso.",
    url: "blog/kos-osobne.html",
    keywords: "kos grécko grecko osobne dodekanézy dodekanezy caravia beach marmari vietor poseidon mobil plaka forest pávy pavy paradise beach agios stefanos asklepion hippokrates therma springs zia kefalos cavo paradiso limionas nisyros autopia rentals",
  },
  {
    type: "Článok",
    title: "5 zaujímavostí Stredomoria, o ktorých nie každý vie",
    description: "Prvá časť seriálu o menej známych príbehoch Stredomoria: rybárske dediny, slovinské pobrežie, Menorca, Málaga a trulli v Apúlii.",
    url: "blog/5-zaujimavosti-stredomoria-1.html",
    keywords: "stredomorie zaujímavosti zaujimavosti seriál serial rybárske dediny rybarske dediny portofino naoussa paros marsaxlokk slovinsko slovinské pobrežie slovinske pobrezie piran portorož portoroz izola koper menorca malaga málaga apúlia apulia alberobello trulli taliansko grécko grecko španielsko spanielsko malta",
  },
  {
    type: "Článok",
    title: "Zakynthos osobne: útesy, korytnačky a výhľady",
    description: "Osobná skúsenosť zo Zakynthosu: Laganas, Navagio, Myzithres, Xigia, Dafni, Banana Beach, korytnačky a praktické rady.",
    url: "blog/zakynthos-osobne.html",
    keywords: "zakynthos zakyntos grécko grecko laganas navagio myzithres xigia dafni banana beach gerakas kalamaki cameo island porto limnionas korakonissi marathonisi korytnačky korytnacky caretta caretta pláže plaze útesy utesy výhľady vyhlady požičanie auta pozicanie auta",
  },
  {
    type: "Video",
    title: "KOS nás úplne prekvapil: Poseidón nám zobral mobil... a potom sa stalo niečo neuveriteľné",
    description: "Video z gréckeho ostrova Kos: more, pláže, ostrovná atmosféra a dovolenkový pohľad na Grécko.",
    url: "videa.html?krajina=grecko",
    keywords: "kos grécko grecko video youtube ostrov more pláže plaze dovolenka dodekanézy dodekanezy poseidon mobil",
  },
  {
    type: "Podcast",
    title: "Kos osobne: Ostrov vetra, divokých pláží a príbehu s Poseidónom",
    description: "Podcast o gréckom Kose, vetre, divokých plážach a dovolenkovom príbehu s Poseidónom.",
    url: "audio.html?krajina=grecko",
    keywords: "kos grécko grecko podcast spotify vietor divoké pláže divoke plaze poseidon mobil dodekanézy dodekanezy",
  },
  {
    type: "Video",
    title: "Zakynthos osobne: pláže, útesy a výhľady",
    description: "Video zo Zakynthosu: pláže, útesy, vyhliadky, Laganas a ostrovná dovolenková atmosféra.",
    url: "videa.html?krajina=grecko",
    keywords: "zakynthos zakyntos grécko grecko video youtube pláže plaze útesy utesy výhľady vyhlady laganas navagio myzithres xigia gerakas marathonisi",
  },
  {
    type: "Podcast",
    title: "Zakynthos osobne: ostrov útesov a korytnačiek",
    description: "Podcast o Zakynthose, plážach, výhľadoch, korytnačkách a praktických dojmoch z ostrova.",
    url: "audio.html?krajina=grecko",
    keywords: "zakynthos zakyntos grécko grecko podcast spotify pláže plaze útesy utesy korytnačky korytnacky laganas navagio marathonisi",
  },
  {
    type: "Článok",
    title: "Slováci po pandémii opäť lietajú viac",
    description: "Koľko Slovákov lietalo pred pandémiou, počas covidu a dnes – a aký podiel môže smerovať do Stredomoria.",
    url: "blog/kolko-slovakov-lieta-do-stredomoria.html",
    keywords: "slováci slovaci lietajú lietaju slováci lietajú slovaci lietaju lietanie pandémia pandemia covid stredomorie cesty lietadlom štatistika statistika štatistický úrad sr tasr dovolenka more 2025 2026 bratislava ryanair odhad výhľad",
  },
  {
    type: "Článok",
    title: "8 praktických rád pre dovolenku v Stredomorí",
    description: "Menej známe tipy pre dovolenku v Stredomorí, ktoré ti môžu ušetriť stres, čas aj peniaze.",
    url: "blog/8-praktickych-rad-stredomorie.html",
    keywords: "stredomorie dovolenka praktické rady prakticke rady cestovanie pláže plaze hotel ubytovanie more vstup do mora topánky do vody topanky do vody meškanie letu meskanie letu cestovka ostrov pobrežie",
  },
  {
    type: "Článok",
    title: "Kde sa more mení na biele zlato",
    description: "Soľné panvy, ružové lagúny a plameniaky v Stredomorí: Sicília, Cyprus, Camargue, Gozo a Ston.",
    url: "blog/solne-panvy-stredomoria.html",
    keywords: "sol soľné panvy lagúny plameniaky taliansko sicília trapani cyprus larnaka francúzsko camargue malta gozo chorvátsko ston príroda",
  },
  {
    type: "Článok",
    title: "Malta v júli: koncerty, more a horúčavy",
    description: "Priama linka z Bratislavy, Isle of MTV, Valletta, Comino a praktické tipy na horúci júl.",
    url: "blog/malta-jul-isle-of-mtv-more-horucavy.html",
    keywords: "malta jul júl isle of mtv katy perry valletta comino koncert more horucavy horúčavy bratislava",
  },
  {
    type: "Článok",
    title: "5 najlepšie hodnotených pláží Stredomoria v EÚ",
    description: "Elafonissi, Balos, La Pelosa, Falassarna a Playa de Muro v jednom plážovom výbere.",
    url: "top-5-plazi-stredomoria-eu.html",
    keywords: "pláže stredomorie eu elafonissi balos la pelosa falassarna playa de muro kréta sardínia mallorca grécko taliansko španielsko",
  },
  {
    type: "Článok",
    title: "Amalfské pobrežie bez stresu",
    description: "Praktický sprievodca po Amalfskom pobreží, Ravelle, doprave a 3-dňovom itinerári.",
    url: "blog-amalfi-pobrezie.html",
    keywords: "amalfi ravello neapol salerno taliansko pobrežie itinerár doprava",
  },
  {
    type: "Flash správa",
    title: "Technická porucha lietadla narušila lety medzi Bratislavou a Zakynthosom",
    description: "Potvrdená aktualizácia meškania Smartwings: QS1518 odletel o 17:59 a návratový QS1519 pristál v Bratislave o 22:51.",
    url: "spravy/smartwings-zakynthos-bratislava-potvrdene-casy-2026.html",
    keywords: "smartwings bratislava zakynthos zakyntos qs1518 qs1519 technická porucha technicka porucha meškanie meskanie 17:59 22:51 hotel poukážky poukazky burger king kompenzácia kompenzacia eu261 250 eur",
  },
  {
    type: "Flash správa",
    title: "Technická porucha narušila lety medzi Bratislavou a Zakynthosom",
    description: "Let Smartwings QS1518 má približne 13-hodinové meškanie a cestujúcich zo Zakynthosu po čakaní odviezli späť do hotelov.",
    url: "spravy/smartwings-zakynthos-bratislava-meskanie-2026.html",
    keywords: "smartwings zakynthos zakyntos bratislava letisko qs1518 qs1519 ok-tvs technická porucha technicka porucha meškanie meskanie cestujúci cestujuci hotel kompenzácia kompenzacia eu261 flightradar24",
  },
  {
    type: "Flash správa",
    title: "Požiar v provincii Almería má najmenej 12 obetí",
    description: "Bezpečnostné upozornenie pre cestujúcich do východnej Andalúzie: sledujte výstrahy, uzávery ciest a evakuačné pokyny v dotknutej časti provincie Almería.",
    url: "spravy/almeria-poziar-evakuacia-2026.html",
    keywords: "spanielsko španielsko almeria almería poziar požiar los gallardos bedar bédar andaluzia andalúzia evakuacia evakuácia hasiči hasici bezpečnosť bezpecnost dovolenkari dovolenkári",
  },
  {
    type: "Flash správa",
    title: "EasyJet a sardínske letiská čakajú štrajky",
    description: "Praktické upozornenie pre cestujúcich do Talianska: 21. júla 2026 sú nahlásené štrajky easyJetu a pracovníkov letísk Olbia a Alghero.",
    url: "spravy/easyjet-sardinia-letiska-strajky-2026.html",
    keywords: "taliansko easyjet sardinia sardínia sardinie olbia alghero letisko letiská lety štrajk strajk palubný personál 21 júl jul 2026 meškanie zrušenie",
  },
  {
    type: "Flash správa",
    title: "Štrajk trajektov na menšie sicílske ostrovy",
    description: "Na 17. až 18. júla 2026 je nahlásený štrajk trajektov Caronte & Tourist Isole Minori na menšie sicílske ostrovy.",
    url: "spravy/sicilia-trajekty-mensie-ostrovy-strajk-2026.html",
    keywords: "sicília sicilia trajekty štrajk strajk caronte tourist isole minori liparské ostrovy liparske egadské egadske ustica pantelleria 17 júl 18 júl 2026 trajekt",
  },
  {
    type: "Flash správa",
    title: "Zakynthos: núdzové pristátie gréckeho F-16",
    description: "Na letisku Zakynthos núdzovo pristálo grécke vojenské lietadlo F-16. Pilot je v poriadku a cestujúci majú sledovať stav letov.",
    url: "spravy/zakynthos-f16-nudzove-pristatie-2026.html",
    keywords: "zakynthos zakyntos grécko grecko f-16 f16 núdzové pristátie nudzove pristatie letisko pilot haf grécke letectvo vojenské lietadlo meškania lety dovolenka",
  },
  {
    type: "Flash správa",
    title: "Za 50 € autobusom k Jadranu",
    description: "SAD Trenčín spúšťa jednodňové kúpanie pri mori v Chorvátsku. Obojsmerná jazda má stáť 50 € a termín je 10. až 11. júla 2026.",
    url: "spravy/sad-trencin-autobusom-k-moru-2026.html",
    keywords: "sad trenčín sad trencin autobusom k moru chorvátsko chorvatsko jadran kúpanie pri mori kupanie pri mori autobus 50 eur split makarska žilina zilina bratislava jednodňový zájazd jednodnovy zajazd",
  },
  {
    type: "Flash správa",
    title: "Etna ochromila letisko v Catanii",
    description: "Sopečný popol z Etny 5. a 6. júla 2026 výrazne obmedzil až pozastavil lety cez letisko Catania na Sicílii.",
    url: "spravy/etna-catania-letisko-popol-2026.html",
    keywords: "etna catania katánia katania sicília sicilia letisko sopečný popol sopecny popol sopka erupcia voragine lety zrušené zrusene presmerované presmerovane palermo euronews ansa el pais",
  },
  {
    type: "Flash správa",
    title: "Dlhé rady na bratislavskom letisku",
    description: "Praktická pripomienka pre cestujúcich po náporoch pri dovolenkových odletoch z Bratislavy.",
    url: "spravy/bratislava-letisko-dlhe-rady-2026.html",
    keywords: "bratislava letisko dlhé rady dlhe rady antalya dovolenka odlety check-in online check-in doklady cestujúci cestujuci dovolenková špička dovolenkova spicka",
  },
  {
    type: "Flash správa",
    title: "Ryanair posilňuje Bratislavu: novinkou bude Turín",
    description: "Zimná sezóna 2026/2027, štvrté bázované lietadlo a južné linky z Bratislavy.",
    url: "spravy/ryanair-bratislava-zima-2026.html",
    keywords: "ryanair bratislava turin turín zima 2026 2027 malaga alicante malta pafos palermo trapani bari neapol lety",
  },
  {
    type: "Flash správa",
    title: "Navagio zostáva zatvorené aj v sezóne 2026",
    description: "Bezpečnostné upozornenie pre pláž Navagio na Zakyntose.",
    url: "spravy/navagio-zatvorene-2026.html",
    keywords: "navagio zakyntos grécko pláž zatvorené bezpečnosť útesy zosuvy vyhliadka",
  },
  {
    type: "Flash správa",
    title: "Košice – Malaga aj mimo leta?",
    description: "Priame spojenie z Košíc do Malagy a cestovanie mimo hlavnej sezóny.",
    url: "spravy/kosice-malaga-aj-mimo-leta.html",
    keywords: "košice kosice malaga ryanair španielsko lety mimo leta andaluzia",
  },
  {
    type: "Flash správa",
    title: "Cyprus: ceny a dovolenka v tieni napätia",
    description: "Cestovateľské upozornenie: Cyprus zostáva otvorený, sleduj lety, ceny a odporúčania.",
    url: "spravy/cyprus-ceny-napatie-2026.html",
    keywords: "cyprus nissi beach ceny bezpečnosť lety napätie blízky východ odporúčania",
  },
  {
    type: "Flash správa",
    title: "Viedeň má zrušiť 100 ml limit na tekutiny",
    description: "Zmena pravidiel pri bezpečnostnej kontrole na letisku Viedeň-Schwechat.",
    url: "spravy/vieden-100ml-limit-tekutiny.html",
    keywords: "viedeň vieden letisko schwechat tekutiny 100 ml batožina letiská kontrola",
  },
  {
    type: "Video",
    title: "Barcelona za 3 dni",
    description: "Plán na Barcelonu: pláž, mesto, futbal a praktické tipy.",
    url: "videa.html?krajina=spanielsko",
    keywords: "barcelona španielsko spanielsko video youtube pláž futbal mesto",
  },
  {
    type: "Video",
    title: "Cyprus v zime",
    description: "Cestovateľský sprievodca po Cypre mimo hlavnej sezóny.",
    url: "videa.html?krajina=cyprus",
    keywords: "cyprus zima video youtube larnaka pafos plameniaky",
  },
  {
    type: "Podcast",
    title: "Amalfi - Ravello",
    description: "Podcast z Talianska o pobreží Amalfi a mestečku Ravello.",
    url: "audio.html?krajina=taliansko",
    keywords: "podcast spotify amalfi ravello taliansko",
  },
  {
    type: "Podcast",
    title: "Malaga - Španielsko",
    description: "Podcast o Malage, mori a cestovaní mimo hlavnej sezóny.",
    url: "audio.html?krajina=spanielsko",
    keywords: "podcast spotify malaga španielsko spanielsko more",
  },
  {
    type: "Destinácia",
    title: "Taliansko",
    description: "Články, videá a podcasty z Talianska, Sicílie, Bari, Amalfi a juhu krajiny.",
    url: "clanky.html?krajina=taliansko",
    keywords: "taliansko sicília sicilia bari amalfi ravello trapani sardínia",
  },
  {
    type: "Destinácia",
    title: "Španielsko",
    description: "Obsah o Španielsku, Barcelone, Malage, Andalúzii a plážach.",
    url: "clanky.html?krajina=spanielsko",
    keywords: "španielsko spanielsko barcelona malaga andalúzia mallorca playa de muro",
  },
  {
    type: "Destinácia",
    title: "Cyprus",
    description: "Obsah o Cypre, Larnake, Nissi Beach, Pafose a cestovaní mimo sezóny.",
    url: "clanky.html?krajina=cyprus",
    keywords: "cyprus larnaka nissi beach pafos plameniaky",
  },
  {
    type: "Destinácia",
    title: "Malta",
    description: "Obsah o Malte, Goze, Vallette, Comine a letných podujatiach.",
    url: "clanky.html?krajina=malta",
    keywords: "malta gozo valletta comino xwejni isle of mtv",
  },
  {
    type: "Destinácia",
    title: "Chorvátsko",
    description: "Obsah o Chorvátsku, Jadrane a Stone.",
    url: "clanky.html?krajina=chorvatsko",
    keywords: "chorvátsko chorvatsko jadran ston solana",
  },
  {
    type: "Destinácia",
    title: "Francúzsko",
    description: "Obsah o francúzskom Stredomorí, Camargue a Azúrovom pobreží.",
    url: "clanky.html?krajina=francuzsko",
    keywords: "francúzsko francuzsko camargue azúrové pobrežie",
  },
  {
    type: "Podstránka",
    title: "Lety zo Slovenska k Stredomoriu",
    description: "Pilotný prehľad letov zo slovenských letísk do stredomorských destinácií.",
    url: "lety.html",
    keywords: "lety bratislava košice kosice poprad piešťany piestany malaga zadar rim charter",
  },
  {
    type: "Podstránka",
    title: "Všetky flash správy",
    description: "Archív bleskových cestovateľských správ.",
    url: "spravy.html",
    keywords: "správy spravy flash bleskove spravy bleskové správy novinky upozornenia",
  },
  {
    type: "Podstránka",
    title: "Všetky články",
    description: "Archív cestovateľských článkov webu Letom po Stredomorí.",
    url: "blog.html",
    keywords: "blog články clanky cestovateľský magazín",
  },
];
