window.LETOM_SEARCH_INDEX = [
  {
    type: "Článok",
    title: "Je plavba výletnou loďou po Stredomorí vhodná pre Slovákov?",
    description: "Kompletný sprievodca pre Slovákov: ceny, doprava do prístavu, kajuty, strava, výlety aj skryté poplatky.",
    url: "blog/plavba-vyletnou-lodou-stredomorie.html",
    keywords: "plavba výletná loď vyletna lod cruise stredomorie slovaci slovensko ceny doprava prístav pristav trieste benátky benatky ravenna civitavecchia barcelona piraeus kajuta kajuty balkón balkon strava výlety vylety poplatky servisné poplatky msc costa royal caribbean",
  },
  {
    type: "Článok",
    title: "Kos osobne: vietor, Poseidónov mobil a pláže",
    description: "Osobná skúsenosť z gréckeho Kosu z roku 2025: Caravia Beach, vietor, auto, Plaka Forest, Asklepion, Therma Springs, Zia, Kefalos a Cavo Paradiso.",
    url: "blog/kos-osobne.html",
    keywords: "kos grécko grecko osobne dodekanézy dodekanezy caravia beach marmari vietor poseidon mobil plaka forest pávy pavy paradise beach agios stefanos asklepion hippokrates therma springs zia kefalos cavo paradiso limionas nisyros autopia rentals",
  },
  {
    type: "Článok",
    title: "5 zaujímavostí Stredomoria, o ktorých nie každý vie",
    description: "Prvá časť seriálu o menej známych príbehoch Stredomoria: rybárske dediny, slovinské pobrežie, Menorca, Málaga a trulli v Apúlii.",
    url: "blog/5-zaujimavosti-stredomoria-1.html",
    keywords: "stredomorie zaujímavosti zaujimavosti seriál serial rybárske dediny rybarske dediny portofino naoussa paros marsaxlokk slovinsko slovinské pobrežie slovinske pobrezie piran portorož portoroz izola koper menorca malaga málaga apúlia apulia alberobello trulli taliansko grécko grecko španielsko spanielsko malta",
  },
  {
    type: "Článok",
    title: "Zakynthos osobne: útesy, korytnačky a výhľady",
    description: "Osobná skúsenosť zo Zakynthosu: Laganas, Navagio, Myzithres, Xigia, Dafni, Banana Beach, korytnačky a praktické rady.",
    url: "blog/zakynthos-osobne.html",
    keywords: "zakynthos zakyntos grécko grecko laganas navagio myzithres xigia dafni banana beach gerakas kalamaki cameo island porto limnionas korakonissi marathonisi korytnačky korytnacky caretta caretta pláže plaze útesy utesy výhľady vyhlady požičanie auta pozicanie auta",
  },
  {
    type: "Video",
    title: "KOS nás úplne prekvapil: Poseidón nám zobral mobil... a potom sa stalo niečo neuveriteľné",
    description: "Video z gréckeho ostrova Kos: more, pláže, ostrovná atmosféra a dovolenkový pohľad na Grécko.",
    url: "videa.html?krajina=grecko",
    keywords: "kos grécko grecko video youtube ostrov more pláže plaze dovolenka dodekanézy dodekanezy poseidon mobil",
  },
  {
    type: "Podcast",
    title: "Kos osobne: Ostrov vetra, divokých pláží a príbehu s Poseidónom",
    description: "Podcast o gréckom Kose, vetre, divokých plážach a dovolenkovom príbehu s Poseidónom.",
    url: "audio.html?krajina=grecko",
    keywords: "kos grécko grecko podcast spotify vietor divoké pláže divoke plaze poseidon mobil dodekanézy dodekanezy",
  },
  {
    type: "Video",
    title: "Zakynthos osobne: pláže, útesy a výhľady",
    description: "Video zo Zakynthosu: pláže, útesy, vyhliadky, Laganas a ostrovná dovolenková atmosféra.",
    url: "videa.html?krajina=grecko",
    keywords: "zakynthos zakyntos grécko grecko video youtube pláže plaze útesy utesy výhľady vyhlady laganas navagio myzithres xigia gerakas marathonisi",
  },
  {
    type: "Podcast",
    title: "Zakynthos osobne: ostrov útesov a korytnačiek",
    description: "Podcast o Zakynthose, plážach, výhľadoch, korytnačkách a praktických dojmoch z ostrova.",
    url: "audio.html?krajina=grecko",
    keywords: "zakynthos zakyntos grécko grecko podcast spotify pláže plaze útesy utesy korytnačky korytnacky laganas navagio marathonisi",
  },
  {
    type: "Článok",
    title: "Slováci po pandémii opäť lietajú viac",
    description: "Koľko Slovákov lietalo pred pandémiou, počas covidu a dnes – a aký podiel môže smerovať do Stredomoria.",
    url: "blog/kolko-slovakov-lieta-do-stredomoria.html",
    keywords: "slováci slovaci lietajú lietaju slováci lietajú slovaci lietaju lietanie pandémia pandemia covid stredomorie cesty lietadlom štatistika statistika štatistický úrad sr tasr dovolenka more 2025 2026 bratislava ryanair odhad výhľad",
  },
  {
    type: "Článok",
    title: "8 praktických rád pre dovolenku v Stredomorí",
    description: "Menej známe tipy pre dovolenku v Stredomorí, ktoré ti môžu ušetriť stres, čas aj peniaze.",
    url: "blog/8-praktickych-rad-stredomorie.html",
    keywords: "stredomorie dovolenka praktické rady prakticke rady cestovanie pláže plaze hotel ubytovanie more vstup do mora topánky do vody topanky do vody meškanie letu meskanie letu cestovka ostrov pobrežie",
  },
  {
    type: "Článok",
    title: "Kde sa more mení na biele zlato",
    description: "Soľné panvy, ružové lagúny a plameniaky v Stredomorí: Sicília, Cyprus, Camargue, Gozo a Ston.",
    url: "blog/solne-panvy-stredomoria.html",
    keywords: "sol soľné panvy lagúny plameniaky taliansko sicília trapani cyprus larnaka francúzsko camargue malta gozo chorvátsko ston príroda",
  },
  {
    type: "Článok",
    title: "Malta v júli: koncerty, more a horúčavy",
    description: "Priama linka z Bratislavy, Isle of MTV, Valletta, Comino a praktické tipy na horúci júl.",
    url: "blog/malta-jul-isle-of-mtv-more-horucavy.html",
    keywords: "malta jul júl isle of mtv katy perry valletta comino koncert more horucavy horúčavy bratislava",
  },
  {
    type: "Článok",
    title: "5 najlepšie hodnotených pláží Stredomoria v EÚ",
    description: "Elafonissi, Balos, La Pelosa, Falassarna a Playa de Muro v jednom plážovom výbere.",
    url: "top-5-plazi-stredomoria-eu.html",
    keywords: "pláže stredomorie eu elafonissi balos la pelosa falassarna playa de muro kréta sardínia mallorca grécko taliansko španielsko",
  },
  {
    type: "Článok",
    title: "Amalfské pobrežie bez stresu",
    description: "Praktický sprievodca po Amalfskom pobreží, Ravelle, doprave a 3-dňovom itinerári.",
    url: "blog-amalfi-pobrezie.html",
    keywords: "amalfi ravello neapol salerno taliansko pobrežie itinerár doprava",
  },
  {
    type: "Flash správa",
    title: "Technická porucha lietadla narušila lety medzi Bratislavou a Zakynthosom",
    description: "Potvrdená aktualizácia meškania Smartwings: QS1518 odletel o 17:59 a návratový QS1519 pristál v Bratislave o 22:51.",
    url: "spravy/smartwings-zakynthos-bratislava-potvrdene-casy-2026.html",
    keywords: "smartwings bratislava zakynthos zakyntos qs1518 qs1519 technická porucha technicka porucha meškanie meskanie 17:59 22:51 hotel poukážky poukazky burger king kompenzácia kompenzacia eu261 250 eur",
  },
  {
    type: "Flash správa",
    title: "Technická porucha narušila lety medzi Bratislavou a Zakynthosom",
    description: "Let Smartwings QS1518 má približne 13-hodinové meškanie a cestujúcich zo Zakynthosu po čakaní odviezli späť do hotelov.",
    url: "spravy/smartwings-zakynthos-bratislava-meskanie-2026.html",
    keywords: "smartwings zakynthos zakyntos bratislava letisko qs1518 qs1519 ok-tvs technická porucha technicka porucha meškanie meskanie cestujúci cestujuci hotel kompenzácia kompenzacia eu261 flightradar24",
  },
  {
    type: "Flash správa",
    title: "Požiar v provincii Almería má najmenej 12 obetí",
    description: "Bezpečnostné upozornenie pre cestujúcich do východnej Andalúzie: sledujte výstrahy, uzávery ciest a evakuačné pokyny v dotknutej časti provincie Almería.",
    url: "spravy/almeria-poziar-evakuacia-2026.html",
    keywords: "spanielsko španielsko almeria almería poziar požiar los gallardos bedar bédar andaluzia andalúzia evakuacia evakuácia hasiči hasici bezpečnosť bezpecnost dovolenkari dovolenkári",
  },
  {
    type: "Flash správa",
    title: "EasyJet a sardínske letiská čakajú štrajky",
    description: "Praktické upozornenie pre cestujúcich do Talianska: 21. júla 2026 sú nahlásené štrajky easyJetu a pracovníkov letísk Olbia a Alghero.",
    url: "spravy/easyjet-sardinia-letiska-strajky-2026.html",
    keywords: "taliansko easyjet sardinia sardínia sardinie olbia alghero letisko letiská lety štrajk strajk palubný personál 21 júl jul 2026 meškanie zrušenie",
  },
  {
    type: "Flash správa",
    title: "Štrajk trajektov na menšie sicílske ostrovy",
    description: "Na 17. až 18. júla 2026 je nahlásený štrajk trajektov Caronte & Tourist Isole Minori na menšie sicílske ostrovy.",
    url: "spravy/sicilia-trajekty-mensie-ostrovy-strajk-2026.html",
    keywords: "sicília sicilia trajekty štrajk strajk caronte tourist isole minori liparské ostrovy liparske egadské egadske ustica pantelleria 17 júl 18 júl 2026 trajekt",
  },
  {
    type: "Flash správa",
    title: "Zakynthos: núdzové pristátie gréckeho F-16",
    description: "Na letisku Zakynthos núdzovo pristálo grécke vojenské lietadlo F-16. Pilot je v poriadku a cestujúci majú sledovať stav letov.",
    url: "spravy/zakynthos-f16-nudzove-pristatie-2026.html",
    keywords: "zakynthos zakyntos grécko grecko f-16 f16 núdzové pristátie nudzove pristatie letisko pilot haf grécke letectvo vojenské lietadlo meškania lety dovolenka",
  },
  {
    type: "Flash správa",
    title: "Za 50 € autobusom k Jadranu",
    description: "SAD Trenčín spúšťa jednodňové kúpanie pri mori v Chorvátsku. Obojsmerná jazda má stáť 50 € a termín je 10. až 11. júla 2026.",
    url: "spravy/sad-trencin-autobusom-k-moru-2026.html",
    keywords: "sad trenčín sad trencin autobusom k moru chorvátsko chorvatsko jadran kúpanie pri mori kupanie pri mori autobus 50 eur split makarska žilina zilina bratislava jednodňový zájazd jednodnovy zajazd",
  },
  {
    type: "Flash správa",
    title: "Etna ochromila letisko v Catanii",
    description: "Sopečný popol z Etny 5. a 6. júla 2026 výrazne obmedzil až pozastavil lety cez letisko Catania na Sicílii.",
    url: "spravy/etna-catania-letisko-popol-2026.html",
    keywords: "etna catania katánia katania sicília sicilia letisko sopečný popol sopecny popol sopka erupcia voragine lety zrušené zrusene presmerované presmerovane palermo euronews ansa el pais",
  },
  {
    type: "Flash správa",
    title: "Dlhé rady na bratislavskom letisku",
    description: "Praktická pripomienka pre cestujúcich po náporoch pri dovolenkových odletoch z Bratislavy.",
    url: "spravy/bratislava-letisko-dlhe-rady-2026.html",
    keywords: "bratislava letisko dlhé rady dlhe rady antalya dovolenka odlety check-in online check-in doklady cestujúci cestujuci dovolenková špička dovolenkova spicka",
  },
  {
    type: "Flash správa",
    title: "Ryanair posilňuje Bratislavu: novinkou bude Turín",
    description: "Zimná sezóna 2026/2027, štvrté bázované lietadlo a južné linky z Bratislavy.",
    url: "spravy/ryanair-bratislava-zima-2026.html",
    keywords: "ryanair bratislava turin turín zima 2026 2027 malaga alicante malta pafos palermo trapani bari neapol lety",
  },
  {
    type: "Flash správa",
    title: "Navagio zostáva zatvorené aj v sezóne 2026",
    description: "Bezpečnostné upozornenie pre pláž Navagio na Zakyntose.",
    url: "spravy/navagio-zatvorene-2026.html",
    keywords: "navagio zakyntos grécko pláž zatvorené bezpečnosť útesy zosuvy vyhliadka",
  },
  {
    type: "Flash správa",
    title: "Košice – Malaga aj mimo leta?",
    description: "Priame spojenie z Košíc do Malagy a cestovanie mimo hlavnej sezóny.",
    url: "spravy/kosice-malaga-aj-mimo-leta.html",
    keywords: "košice kosice malaga ryanair španielsko lety mimo leta andaluzia",
  },
  {
    type: "Flash správa",
    title: "Cyprus: ceny a dovolenka v tieni napätia",
    description: "Cestovateľské upozornenie: Cyprus zostáva otvorený, sleduj lety, ceny a odporúčania.",
    url: "spravy/cyprus-ceny-napatie-2026.html",
    keywords: "cyprus nissi beach ceny bezpečnosť lety napätie blízky východ odporúčania",
  },
  {
    type: "Flash správa",
    title: "Viedeň má zrušiť 100 ml limit na tekutiny",
    description: "Zmena pravidiel pri bezpečnostnej kontrole na letisku Viedeň-Schwechat.",
    url: "spravy/vieden-100ml-limit-tekutiny.html",
    keywords: "viedeň vieden letisko schwechat tekutiny 100 ml batožina letiská kontrola",
  },
  {
    type: "Video",
    title: "Barcelona za 3 dni",
    description: "Plán na Barcelonu: pláž, mesto, futbal a praktické tipy.",
    url: "videa.html?krajina=spanielsko",
    keywords: "barcelona španielsko spanielsko video youtube pláž futbal mesto",
  },
  {
    type: "Video",
    title: "Cyprus v zime",
    description: "Cestovateľský sprievodca po Cypre mimo hlavnej sezóny.",
    url: "videa.html?krajina=cyprus",
    keywords: "cyprus zima video youtube larnaka pafos plameniaky",
  },
  {
    type: "Podcast",
    title: "Amalfi - Ravello",
    description: "Podcast z Talianska o pobreží Amalfi a mestečku Ravello.",
    url: "audio.html?krajina=taliansko",
    keywords: "podcast spotify amalfi ravello taliansko",
  },
  {
    type: "Podcast",
    title: "Malaga - Španielsko",
    description: "Podcast o Malage, mori a cestovaní mimo hlavnej sezóny.",
    url: "audio.html?krajina=spanielsko",
    keywords: "podcast spotify malaga španielsko spanielsko more",
  },
  {
    type: "Destinácia",
    title: "Taliansko",
    description: "Články, videá a podcasty z Talianska, Sicílie, Bari, Amalfi a juhu krajiny.",
    url: "clanky.html?krajina=taliansko",
    keywords: "taliansko sicília sicilia bari amalfi ravello trapani sardínia",
  },
  {
    type: "Destinácia",
    title: "Španielsko",
    description: "Obsah o Španielsku, Barcelone, Malage, Andalúzii a plážach.",
    url: "clanky.html?krajina=spanielsko",
    keywords: "španielsko spanielsko barcelona malaga andalúzia mallorca playa de muro",
  },
  {
    type: "Destinácia",
    title: "Cyprus",
    description: "Obsah o Cypre, Larnake, Nissi Beach, Pafose a cestovaní mimo sezóny.",
    url: "clanky.html?krajina=cyprus",
    keywords: "cyprus larnaka nissi beach pafos plameniaky",
  },
  {
    type: "Destinácia",
    title: "Malta",
    description: "Obsah o Malte, Goze, Vallette, Comine a letných podujatiach.",
    url: "clanky.html?krajina=malta",
    keywords: "malta gozo valletta comino xwejni isle of mtv",
  },
  {
    type: "Destinácia",
    title: "Chorvátsko",
    description: "Obsah o Chorvátsku, Jadrane a Stone.",
    url: "clanky.html?krajina=chorvatsko",
    keywords: "chorvátsko chorvatsko jadran ston solana",
  },
  {
    type: "Destinácia",
    title: "Francúzsko",
    description: "Obsah o francúzskom Stredomorí, Camargue a Azúrovom pobreží.",
    url: "clanky.html?krajina=francuzsko",
    keywords: "francúzsko francuzsko camargue azúrové pobrežie",
  },
  {
    type: "Podstránka",
    title: "Lety zo Slovenska k Stredomoriu",
    description: "Pilotný prehľad letov zo slovenských letísk do stredomorských destinácií.",
    url: "lety.html",
    keywords: "lety bratislava košice kosice poprad piešťany piestany malaga zadar rim charter",
  },
  {
    type: "Podstránka",
    title: "Všetky flash správy",
    description: "Archív krátkych cestovateľských správ Letom v skratke.",
    url: "spravy.html",
    keywords: "správy spravy flash letom v skratke novinky upozornenia",
  },
  {
    type: "Podstránka",
    title: "Všetky články",
    description: "Archív cestovateľských článkov webu Letom po Stredomorí.",
    url: "blog.html",
    keywords: "blog články clanky cestovateľský magazín",
  },
];





